### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by msadowski** [mawildoer/cycloidal_generator#1]
Hi!

Thanks a lot for sharing this project! I noticed that this project doesn't specify any licence, meaning it defaults to "all rights reserved" in theory forbidding others from reproducing your work. Not sure if that was your intention for this project!

**Comment by mawildoer** [comment]
Hi mate,

Good pick. 

Fixed with an unlicence. 

Just saw you (or someone else at weekly robotics) featured the project late last year. Kudos!

**Comment by msadowski** [comment]
Thanks a lot! It was me that featured that in Weekly Robotics last year (https://weeklyrobotics.com/weekly-robotics-12) and I also featured it in [Awesome Weekly Robotics](https://github.com/msadowski/awesome-weekly-robotics) (still WIP though).

**Comment by gops** [comment]
Also, any reference to the equation selected ?
