### ISSUE TITLE
Eccentricity

### ISSUE THREAD

**Issue by abgin** [mawildoer/cycloidal_generator#4]
Hello, i downloaded your cycloidal generator and it works! Thanks!
But i need a bigger eccentricity. When i look the python file, i observe that E = 0.5*Rr (roller radius) (line 43). Is that what you wanted? I saw that E has to be <d/2 (d=roller diameter).
When i modify the line 43 as : E = Rr, the rotor is not well generated. 
Could you help me? 

The answer might be obvious but my programming skills are low ^^ I don't really understand python.

Thanks, have a nice day.
Kind regards,
Antoine

**Comment by mawildoer** [comment]
Hi Abgin, 

I'm sorry, but unfortunately I can not help. I no longer have access Fusion360. 

There's another generator based on similar maths which is being more actively developed: https://github.com/colinmsnow/fusionCycloidal
